// Fichier généré par tools/salle_boss_dofus.py : ne pas modifier à la main (relancer le script).
// Composition (monstres distincts) de la salle du boss de chaque donjon.
export default {
  cat: "Donjons",
  items: [
    ["Quelle est la composition de la salle du boss du donjon « Crypte de Kardorim » ?", "kardorim, Chafer Sergent, Chafer Piquier, Chafer Eclaireur, Chafer Furtif, Chafer Débutant", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Château Ensablé » ?", "Mob l'Éponge, Pichon Kloune, Pichon Blanc, Pichon Orange, Pichon Vert, Pichon Nleu", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Cour du Bouftou Royal » ?", "Bouftou Royal, Bouftou Noir, Chef de Guerre Bouftou, Bouftou", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Tofus » ?", "tofoune, Tofu Ventripotent, Batofu, Tofukaz, Tofu noir, Tofu", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Bworks » ?", "Bwork, Bwork Mage, Bworkette, Bwork Archer", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Squelettes » ?", "Chafer Rönin, Chafer Draugr, Rib, Chafer Fantassin, Chafer, Chafer Invisible", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Cache de Kankreblath » ?", "Cafarcher, Pyrasite, Kankreblath, Mirgrillon, Céglumen, Sakarien", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Scarafeuilles » ?", "Scarabosse Doré, Scarafeuille Noir, Scarafeuille Blanc, Scarafeuille Bleu, Scarafeuille Vert, Scarafeuille Rouge", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Maison Fantôme » ?", "Chafer d'Elite, Maître Vampire, Boostache, Kwoan, Boostache Prépubère, Gargouille, Vampire, Noeul", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Caverne des Bulbes » ?", "Bulbig Brozeur, Bulbuisson, Bulbiflore, Bulbambou, Araknawa", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Forgerons » ?", "Il y a 5 Or à piocher sur la carte, Forgeron Sombre, Mineur Sombre, Coffre des Forgerons, Boulanger Sombre, Bandit du clan des Roublards", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Grotte Hesque » ?", "Corailleur, Corailleur Magistral, Palmifleur Malibout, Palmifleur Morito, Palmifleur Passaoh, Palmifleur Kouraçao, Crustorail Malibout, Crustorail Kouraçao", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Nid du Kwakwa » ?", "Kwak de Vent, Kwak de Glace, Kwak de Terre, Kwakwa, Kwak de Flamme", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Larves » ?", "Shin Larve, Larve Dorée, Larve Rubis, Larve Émeraude, Larve Saphir", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Clos des Blops » ?", "Blop Multicolor Royal, Blop Reinette Royal, Blop Indigo Royal, Blop Griotte Royal, Blop Coco Royal, Tronkoblop, Blopignon", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Gelaxième Dimension » ?", "Gelée Royale Bleue, Gelée Royale Citron, Gelée Royale Fraise, Gelée Royale Menthe, Gelée Bleue, Gelée Citron, Gelée Fraise, Gelée Menthe", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Village Kanniboul » ?", "Kanniboul Tam, Kanniboul Jav, Kanniboul Ebil, Kanniboul Sarbak, Kanniboul Eth, Kanniboul Ark", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Fonderie des Waddicts » ?", "Mawabouaino, Wadnozéam, Warkaïk, Waccro, Wadulant", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Château du Wa Wabbit » ?", "Wa Wabbit, Grand Pa Wabbit, Wo Wabbit", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Pitons Rocheux des Craqueleurs » ?", "Craqueleur Légendaire, Craqueboule, Craqueleur, Élémenterre", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Épreuve de Draegnerys » ?", "Draegnerys, Dragoeuf Argile, Dragoeuf Charbon, Dragoeuf Albatre, Dragoeuf Calcaire, Dragoeuf Ardoise", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Cale de l'Arche d'Otomaï » ?", "Barbroussa, Gourlo le Terrible, Sparo, Le Flib", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Laboratoire de Brumen Tinctorias » ?", "Nelween, Crowneille, Macien, Scorbute", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Repaire de Daïgoro » ?", "Kitsou Nere, Daïgoro, Kitsou Nae, Kitsou Nakwa, Kitsou Nufeu", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Cimetière des Mastodontes » ?", "Ouroboulos, Fennex, Lélhyène, Mantiscore, Boulépique, Scordion Bleu, Léolhyène", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Terrier du Wa Wabbit » ?", "Wa Wobot, Black Wo Wabbit, Wobot Kiafin, Tiwobot, Black Wo Wabbit 80), Wobot, Blanc Pa Wabbit", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Domaine Ancestral » ?", "Abraknyde Ancestral, Abrakne Sombre, Abraknyde Sombre, Araknotron", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Chapiteau des Magik Riktus » ?", "Choudini, Bozoteur, Roukouto, Graboule", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Bateau du Chouque » ?", "Ivremor, Ricanif, Le Chouque, Nakunbra, Canondorf, Boomba", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Antre de la Reine Nyée » ?", "Arapex, Dardalaine, Reine Nyée, Néfileuse, Saltik, Gargantûl", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Antre du Dragon Cochon » ?", "Dragon Cochon, Don Dorgan, Don Duss Ang, Cochon de Farle, Porsalu", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Potager d'Halouine » ?", "Cauchemarakne, Champêtrouille, Lanverne, Halouine, Chauffe-Soutrille", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Repaire du Kharnozor » ?", "Kharnozor, Dragoss Charbon, Dragoss Argile, Dragoss Protéiforme, Dragoss Ardoise, Dragoss Calcaire", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Caverne du Koulosse » ?", "Koulosse, Bouftou des Cavernes", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Tanière du Meulou » ?", "Meulou, Muloubard, Mulounoké, Cocholou", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Arbre de Moon » ?", "Domoizelle, Dostrogo, Moon, Trukikol, Gloutovore, Fourbasse", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Bambusaie de Damadrya » ?", "Damadrya, Bulbiflore, Floristile, Bulbuisson, Bambouto, Grenufar", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Bibliothèque du Maître Corbac » ?", "Maître Corbac, Horace le Corbac Apprivoisé, Kapotie le Buveur, Rono le Renarbo", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Garde-manger du Rat Blanc » ?", "Rat Bajoie, Rat Croc, Rat Blanc, Rat Basher", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Sousouricière du Rat Noir » ?", "Rat Batteur, Rat de Marais, Rat Noir, Rat Klure", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Goulet du Rasboul » ?", "Kilibriss, Silf le Rasboul Majeur, Bitouf des Plaines, Kido, Craqueleur Poli, Mufafah", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Antre du Blop Multicolore Royal » ?", "Blop Multicolor Royal, Blop Reinette Royal, Blop Indigo Royal, Blop Griotte Royal, Blop Coco Royal, Tronkoblop, Blopignon", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Antre de Crocabulia » ?", "Crocabulia, Dragoeuf Volant, Dragoeuf Guerrier, Dragueuse, Dragoss Noir Éveillé, Dragoss de Saphir Éveillé, Dragoss Doré Éveillé, Dragoss Blanc Éveillé", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Repaire des Pandikazes » ?", "Maître Pandore, Pandikwakaze, Pandikaze Aérien, Pandulkaze, Pandikaze Vertige", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Centre du Labyrinthe du Minotoror » ?", "Minotot, Mominotor, Minotoror, Déminoboule, Gamino, Scaratos", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Serre du Royalmouth » ?", "Boufmouth Légendaire, Royalmouth, Boufmouth de Guerre, Boufmouth, Bouftonmouth", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Repaire de Skeunk » ?", "Skeunk, Émeraude, Saphira, Rubise, Diamantine, Poupée Affâmée", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Tofulailler Royal » ?", "Tofu Royal, Tofu Dodu, Tofubine, Tofutoflamme, Vilain Petit Tofu", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Sanctuaire de Torkélonia » ?", "Torkélonia, Caïguille, Kashkaille, Alashass, Voapah, Cronnibal", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Croquanterie » ?", "Croqueleur, Glourson Guimauve, Kakoalak, Chocoskargo, Glourson Guimauvse, Mansocolat, Kwakao", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Caverne d'El Piko » ?", "Lévito, Cactoblongo, Cactiflore, El Piko", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Volière de la Haute Truche » ?", "Haute Truche, Gruche, Truchmuche, Truchtine, Truchine", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Vallée de la Dame des eaux » ?", "Nagate, Akakwa, Kwamouraï, Kokom, Sarkapwane, Betto", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Atelier du Tanukouï San » ?", "Tanukouï San, Shinibaru, Ishigro Pake, Tétonuki, Lolojiki, Parashukouï", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Clairière du Chêne Mou » ?", "Chêne Mou, Branche Soignante, Branche Invocatrice, Abraknyde Sombre Irascible", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Fabrique de foux d'artifice » ?", "Founoroshi, Founamboul, Rouquette, Boumbardier", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Dojo du Vent » ?", "Hanshi, Shihan, Kurookin, Lichagoro, Ino-Naru Fangshu, Uchiwang", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Excavation du Mansot Royal » ?", "Mansot royal, Fu Mansot, Shamansot, Mamansot, Mansobèse, Timansot", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon des Firefoux » ?", "Péki Péki", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Laboratoire du Tynril » ?", "Tynril Déconcerté, Tynril Consterné, Tynril Ahuri, Tynril Perfide", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Épave du Grolandais violent » ?", "Ben le Ripate, Vigie Pirate, Harpirate, Fantimonier, Fantômat, Fantomalamère, Fancrôme", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Repaire de Sphincter Cell » ?", "Rat Blanc, Rat Noir, Sphincter Cell, Ramane, Rat Caille, Rat Botteur, Rat Pine, Rat Fraîchi", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Grotte de Kanigroula » ?", "Kanihilan, Kanigroula, Orfélin, Kaniblou", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Canopée du Kimbo » ?", "Kaskargo, Abrakleur Clair, Bitouf Aérien, Kimbo, Poolay, Meupette", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Salle du Minotot » ?", "Minotot, Mominotor, Minotoror, Déminoboule, Gamino, Scaratos", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Hypogée de l'Obsidiantre » ?", "Obsidiantre, Mofette, Fumrirolle, Solfataré, Crapeur, Atomystique", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Tombe du Shogun Tofugawa » ?", "Shogun Tofugawa, Tambouraï, Kabushido, Jiangshi-Nobi, Onabu-Geisha, Tsukinochi", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Demeure des Esprits » ?", "Koumiho, Madura, Bakazako, Onigori, Tsume-bozu, Kaonashi", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Boyau du Père Ver » ?", "Père Ver, Pikténia, Morsquale, Trémorse", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Tanière Givrefoux » ?", "Tengu Givrefoux, Fuji Givrefoux Nourricière, Yokaï Givrefoux, Yomi Givrefoux, Kami Givrefoux, Maho Givrefoux, Soryo Givrefoux", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Grotte du Bworker » ?", "Bworker, Bwork Élémental de Feu, Cybwork, Mama Bwork", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Antre du Korriandre » ?", "Korriandre, Fongeur, Mérulette, Dramanite, Abrazif, Fistulor", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Temple du Grand Ougah » ?", "Tromperelle, Champ à Gnons, Champmane, Ougah", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Camp du Comte Razof » ?", "Viandargh, Crâmbo, Nemroz, Comte Razof", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Antichambre des Gloursons » ?", "Glourséleste, Meliglours, Glouragan, Glourmand, Boulglours, Apériglours, Gloursaya", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Donjon de la mine de Sakaï » ?", "Grolloum, Gobus, Perkü, Marôdeur, Courtilleur, Ouilleur, Sapeur, Gobosteur", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Cavernes du Kolosso » ?", "Kolosso, Professeur Xa, Blérom, Croleur, Blérice, Blérauve, Wolvero, Fleuro", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Pyramide d'Ombre » ?", "Ombre, Caznoar, Sombléro, Noctulule, Brutopak, Panterreur", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Temple du dieu Kao » ?", "Prêtresse de Kao, Pralicienne, Torréfactueur, Chocoligarque, Cabosseur", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Manoir des Katrepat » ?", "Anerice la Shushess, Goultime, Kérigoule, Houligane, Goulafre, Pipisteuse", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Tour de Bethel » ?", "Bethel Akarna, Zombruth, Crânonier, Tournoyé, Macrab, Funespadon", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Vaisseau du Capitaine Meno » ?", "Capitaine Meno, Tilamproie, Mantaze, Gambaf, Mol Usk, Crabe Yoloniste", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Palais de Dantinéa » ?", "Dantinéa, Diondin, Rilur, Tryde, Tourthon, Poulpée", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Brasserie du roi Dazak » ?", "Dazak Martegel, Tanklume, Kasrok, Boufbos, Barbélier, Vatenbière", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Trône de sang » ?", "Guerre, Ravalame, Trancharnier, Olgoth, Fléaunide, Macabrateur", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Belvédère d'Ilyzaelle » ?", "Ilyzaelle, Crpame, Ectorche, Esprigné, Chause, Crâme, Feutôme", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Salons privés de Klime » ?", "Klime, Cuirboule, Empaillé, Grodruche, Harrogant, Peunch", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Temple de Koutoulou » ?", "Larve de Koutoulou, Klûtiste, Li-Fo, Shokkoth, Grofond, N'yalg", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Aquadôme de Merkator » ?", "Merkator, Harpo, Cyclophandre, Eskoglyphe, Pikoleur, Krabouilleur", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Sentence de la balance » ?", "Misère, Ferrailleur, Krèvladal, Désosseur, Dawaj, Skentu", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Forgefroide de Missiz Frizz » ?", "Missiz Frizz, Karkanik, Stalak, Verglasseur, Frimar, Ventrublion", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Laboratoire de Nileza » ?", "Nileza, Dodox 212), Drosérâle, Nessil, Krakal, Krakkal, Dodox, Termystique", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Ventre de la Baleine » ?", "Protozorreur, Verminocule, Tabacille, Virustine, Pataugerme, Bacterrib", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Tour de Solar » ?", "Solar, Klémort, Halbardent 212), Moribombe, Trépavois, Halbardent, Hacharné", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Transporteur de Sylargh » ?", "Sylargh, Brikoglours, Mansordide, Mécanofoux, Mérulor, Méruor, Kanimate", 3, 60],
    ["Quelle est la composition de la salle du boss du donjon « Chambre de Tal Kasha » ?", "Tal Kasha, Griffotep, Momistik, Chakanoubis, Bandleth, Rykaon", 3, 60],
  ],
};
