// Fichier généré par tools/salle_boss_dofus.py : ne pas modifier à la main (relancer le script).
// Les 4 monstres de la dernière salle (celle du boss) de chaque donjon.
export default {
  cat: "Donjons",
  items: [
    ["Quels sont les 4 monstres de la dernière salle du donjon « Crypte de Kardorim » ?", "Kardorim, Chafer Sergent, Chafer Piquier, Chafer Eclaireur", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Château Ensablé » ?", "Mob l'Éponge, Pichon Kloune, Pichon Blanc, Pichon Orange", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Cour du Bouftou Royal » ?", "Bouftou Royal, Bouftou Noir, Chef de Guerre Bouftou, Bouftou", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Donjon des Bworks » ?", "Bwork, Bwork Mage, Bworkette, Bwork Archer", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Donjon des Squelettes » ?", "Chafer Rönin, Chafer Draugr ×3", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Cache de Kankreblath » ?", "Cafarcher, Pyrasite, Kankreblath, Mirgrillon", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Donjon des Scarafeuilles » ?", "Scarabosse Doré, Scarafeuille Noir, Scarafeuille Blanc, Scarafeuille Bleu", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Maison Fantôme » ?", "Chafer d'Elite, Maître Vampire, Boostache, Kwoan", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Caverne des Bulbes » ?", "Bulbig Brozeur, Bulbuisson, Bulbiflore, Bulbambou", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Grotte Hesque » ?", "Corailleur, Corailleur Magistral, Palmifleur Malibout, Palmifleur Morito", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Nid du Kwakwa » ?", "Kwak de Vent, Kwak de Glace, Kwak de Terre, Kwakwa", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Donjon des Larves » ?", "Shin Larve, Larve Dorée, Larve Rubis, Larve Émeraude", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Gelaxième Dimension » ?", "Gelée Royale Bleue, Gelée Royale Citron, Gelée Royale Fraise, Gelée Royale Menthe", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Village Kanniboul » ?", "Kanniboul Tam, Kanniboul Jav, Kanniboul Ebil, Kanniboul Sarbak", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Fonderie des Waddicts » ?", "Mawabouaino, Wadnozéam, Warkaïk, Waccro", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Château du Wa Wabbit » ?", "Wa Wabbit, Grand Pa Wabbit ×2, Wo Wabbit", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Pitons Rocheux des Craqueleurs » ?", "Craqueleur Légendaire, Craqueboule, Craqueleur, Élémenterre", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Épreuve de Draegnerys » ?", "Draegnerys, Dragoeuf Argile, Dragoeuf Charbon, Dragoeuf Albatre", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Cale de l'Arche d'Otomaï » ?", "Barbroussa, Gourlo le Terrible, Sparo, Le Flib", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Laboratoire de Brumen Tinctorias » ?", "Nelween, Crowneille, Macien, Scorbute", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Repaire de Daïgoro » ?", "Kitsou Nere, Daïgoro, Kitsou Nae, Kitsou Nakwa", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Cimetière des Mastodontes » ?", "Ouroboulos, Fennex, Lélhyène, Mantiscore", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Terrier du Wa Wabbit » ?", "Wa Wobot, Black Wo Wabbit, Wobot Kiafin, Tiwobot", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Domaine Ancestral » ?", "Abraknyde Ancestral, Abrakne Sombre, Abraknyde Sombre, Araknotron", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Chapiteau des Magik Riktus » ?", "Choudini, Bozoteur, Roukouto, Graboule", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Bateau du Chouque » ?", "Ivremor, Ricanif, Le Chouque, Nakunbra", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Antre de la Reine Nyée » ?", "Arapex, Dardalaine, Reine Nyée, Néfileuse", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Antre du Dragon Cochon » ?", "Dragon Cochon, Don Dorgan, Don Duss Ang, Cochon de Farle", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Potager d'Halouine » ?", "Cauchemarakne, Champêtrouille, Lanverne, Halouine", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Repaire du Kharnozor » ?", "Kharnozor, Dragoss Charbon, Dragoss Argile, Dragoss Protéiforme", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Caverne du Koulosse » ?", "Koulosse, Bouftou des Cavernes ×3", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Tanière du Meulou » ?", "Meulou, Muloubard, Mulounoké, Cocholou", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Arbre de Moon » ?", "Domoizelle, Dostrogo, Moon, Trukikol", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Bambusaie de Damadrya » ?", "Damadrya, Bulbiflore, Floristile, Bulbuisson", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Garde-manger du Rat Blanc » ?", "Rat Bajoie, Rat Croc, Rat Blanc, Rat Basher", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Sousouricière du Rat Noir » ?", "Rat Batteur, Rat de Marais, Rat Noir, Rat Klure", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Goulet du Rasboul » ?", "Kilibriss, Silf le Rasboul Majeur, Bitouf des Plaines, Kido", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Antre de Crocabulia » ?", "Crocabulia, Dragoeuf Volant, Dragoeuf Guerrier, Dragueuse", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Repaire des Pandikazes » ?", "Maître Pandore, Pandikwakaze, Pandikaze Aérien ×2", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Serre du Royalmouth » ?", "Boufmouth Légendaire, Royalmouth, Boufmouth de Guerre, Boufmouth", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Tofulailler Royal » ?", "Tofu Royal, Tofu Dodu, Tofubine, Tofutoflamme", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Sanctuaire de Torkélonia » ?", "Torkélonia, Caïguille, Kashkaille, Alashass", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Croquanterie » ?", "Croqueleur, Glourson Guimauve, Kakoalak, Chocoskargo", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Caverne d'El Piko » ?", "Lévito, Cactoblongo, Cactiflore, El Piko", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Volière de la Haute Truche » ?", "Haute Truche, Gruche, Truchmuche, Truchtine", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Vallée de la Dame des eaux » ?", "Nagate, Akakwa, Kwamouraï, Kokom", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Atelier du Tanukouï San » ?", "Tanukouï San, Shinibaru, Ishigro Pake, Tétonuki", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Clairière du Chêne Mou » ?", "Chêne Mou, Branche Soignante, Branche Invocatrice, Abraknyde Sombre Irascible", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Fabrique de foux d'artifice » ?", "Founoroshi, Founamboul, Rouquette, Boumbardier", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Excavation du Mansot Royal » ?", "Mansot royal, Fu Mansot, Shamansot, Mamansot", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Épave du Grolandais violent » ?", "Ben le Ripate, Vigie Pirate, Harpirate, Fantimonier", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Repaire de Sphincter Cell » ?", "Rat Blanc, Rat Noir, Sphincter Cell, Ramane", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Grotte de Kanigroula » ?", "Kanihilan, Kanigroula, Orfélin, Kaniblou", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Canopée du Kimbo » ?", "Kaskargo, Abrakleur Clair, Bitouf Aérien, Kimbo", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Hypogée de l'Obsidiantre » ?", "Obsidiantre, Mofette, Fumrirolle, Solfataré", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Tombe du Shogun Tofugawa » ?", "Shogun Tofugawa, Tambouraï, Kabushido ×2", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Demeure des Esprits » ?", "Koumiho, Madura, Bakazako, Onigori", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Boyau du Père Ver » ?", "Père Ver, Pikténia, Morsquale, Trémorse", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Tanière Givrefoux » ?", "Tengu Givrefoux, Fuji Givrefoux Nourricière, Yokaï Givrefoux, Yomi Givrefoux", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Grotte du Bworker » ?", "Bworker, Bwork Élémental de Feu, Cybwork, Mama Bwork", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Antre du Korriandre » ?", "Korriandre, Fongeur, Mérulette, Dramanite", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Camp du Comte Razof » ?", "Viandargh, Crâmbo, Nemroz, Comte Razof", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Antichambre des Gloursons » ?", "Glourséleste, Meliglours, Glouragan, Glourmand", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Donjon de la mine de Sakaï » ?", "Grolloum, Gobus, Perkü, Marôdeur", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Cavernes du Kolosso » ?", "Kolosso, Professeur Xa, Blérom, Croleur", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Pyramide d'Ombre » ?", "Ombre, Caznoar, Sombléro, Noctulule", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Temple du dieu Kao » ?", "Prêtresse de Kao, Pralicienne, Torréfactueur, Chocoligarque", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Manoir des Katrepat » ?", "Anerice la Shushess, Goultime, Kérigoule, Houligane", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Tour de Bethel » ?", "Bethel Akarna, Zombruth, Crânonier, Tournoyé", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Vaisseau du Capitaine Meno » ?", "Capitaine Meno, Tilamproie, Mantaze, Gambaf", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Palais de Dantinéa » ?", "Dantinéa, Diondin, Rilur, Tryde", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Brasserie du roi Dazak » ?", "Dazak Martegel, Tanklume, Kasrok, Boufbos", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Trône de sang » ?", "Guerre, Ravalame, Trancharnier, Olgoth", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Belvédère d'Ilyzaelle » ?", "Ilyzaelle, Crpame, Ectorche, Esprigné", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Salons privés de Klime » ?", "Klime, Cuirboule, Empaillé, Grodruche", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Temple de Koutoulou » ?", "Larve de Koutoulou, Klûtiste, Li-Fo, Shokkoth", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Aquadôme de Merkator » ?", "Merkator, Harpo, Cyclophandre, Eskoglyphe", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Sentence de la balance » ?", "Misère, Ferrailleur, Krèvladal, Désosseur", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Forgefroide de Missiz Frizz » ?", "Missiz Frizz, Karkanik, Stalak, Verglasseur", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Laboratoire de Nileza » ?", "Nileza, Dodox, Drosérâle, Nessil", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Ventre de la Baleine » ?", "Protozorreur, Verminocule, Tabacille, Virustine", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Tour de Solar » ?", "Solar, Klémort, Halbardent, Moribombe", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Transporteur de Sylargh » ?", "Sylargh, Brikoglours, Mansordide, Mécanofoux", 3, 60],
    ["Quels sont les 4 monstres de la dernière salle du donjon « Chambre de Tal Kasha » ?", "Tal Kasha, Griffotep, Momistik, Chakanoubis", 3, 60],
  ],
};
