// Fichier généré par tools/metiers_dofus.py : ne pas modifier à la main (relancer le script).
// Ressources des métiers de récolte : la ressource débloquée à un niveau, et le niveau d'une ressource.
export default {
  cat: "Métiers",
  items: [
    ["Quelle ressource le bûcheron débloque-t-il au niveau 1 ?", "Bois de Frêne", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 20 ?", "Bois de Châtaignier", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 40 ?", "Bois de Noyer", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 60 ?", "Bois de Chêne", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 70 ?", "Bois de Bombu", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 80 ?", "Bois d'Érable", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 90 ?", "Bois d'Oliviolet, Bois de Pin", 3, 35],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 100 ?", "Bois d'If", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 110 ?", "Bois de Bambou", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 120 ?", "Bois de Merisier", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 130 ?", "Bois de Noisetier", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 140 ?", "Bois d'Ébène", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 150 ?", "Bois de Kaliptus", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 160 ?", "Bois de Charme", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 170 ?", "Bois de Bambou Sombre", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 180 ?", "Bois d'Orme", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 190 ?", "Bois de Bambou Sacré", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 200 ?", "Bois de Tremble, Bois d'Aquajou", 3, 35],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Frêne » ?", "1", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Châtaignier » ?", "20", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Noyer » ?", "40", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Chêne » ?", "60", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bombu » ?", "70", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Érable » ?", "80", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Oliviolet » ?", "90", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Pin » ?", "90", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'If » ?", "100", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bambou » ?", "110", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Merisier » ?", "120", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Noisetier » ?", "130", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Ébène » ?", "140", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Kaliptus » ?", "150", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Charme » ?", "160", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bambou Sombre » ?", "170", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Orme » ?", "180", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bambou Sacré » ?", "190", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Tremble » ?", "200", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Aquajou » ?", "200", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 1 ?", "Fer", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 20 ?", "Cuivre", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 40 ?", "Bronze", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 60 ?", "Kobalte", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 80 ?", "Manganèse", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 100 ?", "Étain, Silicate", 3, 35],
    ["Quelle ressource le mineur débloque-t-il au niveau 120 ?", "Argent", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 140 ?", "Bauxite", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 160 ?", "Or", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 180 ?", "Dolomite, Cendrepierre", 3, 35],
    ["Quelle ressource le mineur débloque-t-il au niveau 200 ?", "Obsidienne, Écume de mer, Cristal pliable, Cristal liquide", 3, 35],
    ["À quel niveau de mineur peut-on récolter la ressource « Fer » ?", "1", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cuivre » ?", "20", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Bronze » ?", "40", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Kobalte » ?", "60", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Manganèse » ?", "80", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Étain » ?", "100", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Silicate » ?", "100", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Argent » ?", "120", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Bauxite » ?", "140", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Or » ?", "160", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Dolomite » ?", "180", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cendrepierre » ?", "180", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Obsidienne » ?", "200", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Écume de mer » ?", "200", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cristal pliable » ?", "200", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cristal liquide » ?", "200", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 1 ?", "Ortie", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 20 ?", "Sauge", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 40 ?", "Trèfle à 5 feuilles", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 60 ?", "Menthe Sauvage", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 80 ?", "Orchidée Freyesque", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 100 ?", "Edelweiss", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 120 ?", "Graine de Pandouille", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 140 ?", "Ginseng", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 160 ?", "Belladone", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 180 ?", "Mandragore", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 200 ?", "Perce-Neige, Salikrone, Tulipe en papier", 3, 35],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Ortie » ?", "1", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Sauge » ?", "20", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Trèfle à 5 feuilles » ?", "40", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Menthe Sauvage » ?", "60", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Orchidée Freyesque » ?", "80", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Edelweiss » ?", "100", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Graine de Pandouille » ?", "120", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Ginseng » ?", "140", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Belladone » ?", "160", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Mandragore » ?", "180", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Perce-Neige » ?", "200", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Salikrone » ?", "200", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Tulipe en papier » ?", "200", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 1 ?", "Blé", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 20 ?", "Orge", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 40 ?", "Avoine", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 60 ?", "Houblon", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 80 ?", "Lin", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 100 ?", "Seigle, Riz", 3, 35],
    ["Quelle ressource le paysan débloque-t-il au niveau 120 ?", "Malt", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 140 ?", "Chanvre", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 160 ?", "Maïs", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 180 ?", "Millet", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 200 ?", "Frostiz, Quisnoa", 3, 35],
    ["À quel niveau de paysan peut-on récolter la ressource « Blé » ?", "1", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Orge » ?", "20", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Avoine » ?", "40", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Houblon » ?", "60", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Lin » ?", "80", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Seigle » ?", "100", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Riz » ?", "100", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Malt » ?", "120", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Chanvre » ?", "140", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Maïs » ?", "160", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Millet » ?", "180", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Frostiz » ?", "200", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Quisnoa » ?", "200", 2, 25],
  ],
};
