// Fichier généré par tools/metiers_dofus.py : ne pas modifier à la main (relancer le script).
// Métiers de récolte (ressource débloquée à un niveau, niveau d'une ressource) puis pains, planches et alliages.
export default {
  cat: "Métiers",
  items: [
    ["Quelle ressource le bûcheron débloque-t-il au niveau 1 ?", "Bois de Frêne", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 20 ?", "Bois de Châtaignier", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 40 ?", "Bois de Noyer", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 60 ?", "Bois de Chêne", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 70 ?", "Bois de Bombu", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 80 ?", "Bois d'Érable", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 90 ?", "Bois d'Oliviolet, Bois de Pin", 3, 35],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 100 ?", "Bois d'If", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 110 ?", "Bois de Bambou", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 120 ?", "Bois de Merisier", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 130 ?", "Bois de Noisetier", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 140 ?", "Bois d'Ébène", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 150 ?", "Bois de Kaliptus", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 160 ?", "Bois de Charme", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 170 ?", "Bois de Bambou Sombre", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 180 ?", "Bois d'Orme", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 190 ?", "Bois de Bambou Sacré", 2, 25],
    ["Quelle ressource le bûcheron débloque-t-il au niveau 200 ?", "Bois de Tremble, Bois d'Aquajou", 3, 35],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Frêne » ?", "1", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Châtaignier » ?", "20", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Noyer » ?", "40", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Chêne » ?", "60", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bombu » ?", "70", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Érable » ?", "80", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Oliviolet » ?", "90", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Pin » ?", "90", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'If » ?", "100", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bambou » ?", "110", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Merisier » ?", "120", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Noisetier » ?", "130", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Ébène » ?", "140", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Kaliptus » ?", "150", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Charme » ?", "160", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bambou Sombre » ?", "170", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Orme » ?", "180", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Bambou Sacré » ?", "190", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois de Tremble » ?", "200", 2, 25],
    ["À quel niveau de bûcheron peut-on récolter la ressource « Bois d'Aquajou » ?", "200", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 1 ?", "Fer", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 20 ?", "Cuivre", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 40 ?", "Bronze", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 60 ?", "Kobalte", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 80 ?", "Manganèse", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 100 ?", "Étain, Silicate", 3, 35],
    ["Quelle ressource le mineur débloque-t-il au niveau 120 ?", "Argent", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 140 ?", "Bauxite", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 160 ?", "Or", 2, 25],
    ["Quelle ressource le mineur débloque-t-il au niveau 180 ?", "Dolomite, Cendrepierre", 3, 35],
    ["Quelle ressource le mineur débloque-t-il au niveau 200 ?", "Obsidienne, Écume de mer, Cristal pliable, Cristal liquide", 3, 35],
    ["À quel niveau de mineur peut-on récolter la ressource « Fer » ?", "1", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cuivre » ?", "20", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Bronze » ?", "40", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Kobalte » ?", "60", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Manganèse » ?", "80", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Étain » ?", "100", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Silicate » ?", "100", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Argent » ?", "120", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Bauxite » ?", "140", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Or » ?", "160", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Dolomite » ?", "180", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cendrepierre » ?", "180", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Obsidienne » ?", "200", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Écume de mer » ?", "200", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cristal pliable » ?", "200", 2, 25],
    ["À quel niveau de mineur peut-on récolter la ressource « Cristal liquide » ?", "200", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 1 ?", "Ortie", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 20 ?", "Sauge", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 40 ?", "Trèfle à 5 feuilles", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 60 ?", "Menthe Sauvage", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 80 ?", "Orchidée Freyesque", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 100 ?", "Edelweiss", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 120 ?", "Graine de Pandouille", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 140 ?", "Ginseng", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 160 ?", "Belladone", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 180 ?", "Mandragore", 2, 25],
    ["Quelle ressource l'alchimiste débloque-t-il au niveau 200 ?", "Perce-Neige, Salikrone, Tulipe en papier", 3, 35],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Ortie » ?", "1", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Sauge » ?", "20", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Trèfle à 5 feuilles » ?", "40", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Menthe Sauvage » ?", "60", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Orchidée Freyesque » ?", "80", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Edelweiss » ?", "100", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Graine de Pandouille » ?", "120", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Ginseng » ?", "140", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Belladone » ?", "160", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Mandragore » ?", "180", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Perce-Neige » ?", "200", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Salikrone » ?", "200", 2, 25],
    ["À quel niveau d'alchimiste peut-on récolter la ressource « Tulipe en papier » ?", "200", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 1 ?", "Blé", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 20 ?", "Orge", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 40 ?", "Avoine", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 60 ?", "Houblon", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 80 ?", "Lin", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 100 ?", "Seigle, Riz", 3, 35],
    ["Quelle ressource le paysan débloque-t-il au niveau 120 ?", "Malt", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 140 ?", "Chanvre", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 160 ?", "Maïs", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 180 ?", "Millet", 2, 25],
    ["Quelle ressource le paysan débloque-t-il au niveau 200 ?", "Frostiz, Quisnoa", 3, 35],
    ["À quel niveau de paysan peut-on récolter la ressource « Blé » ?", "1", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Orge » ?", "20", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Avoine » ?", "40", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Houblon » ?", "60", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Lin » ?", "80", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Seigle » ?", "100", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Riz » ?", "100", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Malt » ?", "120", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Chanvre » ?", "140", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Maïs » ?", "160", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Millet » ?", "180", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Frostiz » ?", "200", 2, 25],
    ["À quel niveau de paysan peut-on récolter la ressource « Quisnoa » ?", "200", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 1 ?", "Pain d'Incarnam", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 10 ?", "Michette", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 20 ?", "Carasau", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 30 ?", "Fougasse", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 40 ?", "Pain aux Flocons d'Avoine", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 50 ?", "Pain de Mie", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 60 ?", "Briochette", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 70 ?", "Pain Consistant", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 80 ?", "Biscotte", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 90 ?", "Pain d'Épices", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 100 ?", "Pain de Seigle", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 110 ?", "Pain des Villes", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 120 ?", "Pain aux Céréales", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 130 ?", "Borodinski", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 140 ?", "Pain Gre", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 150 ?", "Mantou", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 170 ?", "Pain des Champs", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 180 ?", "Pain Tahde", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 190 ?", "Brioche Dorée", 2, 25],
    ["Quel pain le paysan débloque-t-il au niveau 200 ?", "Pain de Frostiz", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain d'Incarnam » ?", "1", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Michette » ?", "10", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Carasau » ?", "20", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Fougasse » ?", "30", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain aux Flocons d'Avoine » ?", "40", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain de Mie » ?", "50", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Briochette » ?", "60", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain Consistant » ?", "70", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Biscotte » ?", "80", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain d'Épices » ?", "90", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain de Seigle » ?", "100", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain des Villes » ?", "110", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain aux Céréales » ?", "120", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Borodinski » ?", "130", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain Gre » ?", "140", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Mantou » ?", "150", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain des Champs » ?", "170", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain Tahde » ?", "180", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Brioche Dorée » ?", "190", 2, 25],
    ["À quel niveau de paysan peut-on fabriquer le pain « Pain de Frostiz » ?", "200", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 1 ?", "Planche Agglomérée", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 20 ?", "Planche Contreplaquée", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 40 ?", "Planche à Griller", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 60 ?", "Planche de Surf", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 80 ?", "Planche à Repasser", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 100 ?", "Planche de Toilette", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 120 ?", "Planche à Pâtisserie", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 140 ?", "Planche de Gravure", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 160 ?", "Planche à Pain", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 180 ?", "Planche à Dessin", 2, 25],
    ["Quelle planche le bûcheron débloque-t-il au niveau 200 ?", "Planche de Salut", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche Agglomérée » ?", "1", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche Contreplaquée » ?", "20", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche à Griller » ?", "40", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche de Surf » ?", "60", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche à Repasser » ?", "80", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche de Toilette » ?", "100", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche à Pâtisserie » ?", "120", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche de Gravure » ?", "140", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche à Pain » ?", "160", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche à Dessin » ?", "180", 2, 25],
    ["À quel niveau de bûcheron peut-on fabriquer la planche « Planche de Salut » ?", "200", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 1 ?", "Ferrite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 20 ?", "Aluminite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 30 ?", "Grizite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 40 ?", "Ébonite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 60 ?", "Magnésite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 80 ?", "Bakélélite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 100 ?", "Kouartz, Plaque d'acier", 3, 35],
    ["Quel alliage le mineur débloque-t-il au niveau 120 ?", "Kriptonite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 140 ?", "Kobalite", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 160 ?", "Rutile", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 180 ?", "Pyrute", 2, 25],
    ["Quel alliage le mineur débloque-t-il au niveau 200 ?", "Ardonite", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Ferrite » ?", "1", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Aluminite » ?", "20", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Grizite » ?", "30", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Ébonite » ?", "40", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Magnésite » ?", "60", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Bakélélite » ?", "80", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Kouartz » ?", "100", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Plaque d'acier » ?", "100", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Kriptonite » ?", "120", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Kobalite » ?", "140", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Rutile » ?", "160", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Pyrute » ?", "180", 2, 25],
    ["À quel niveau de mineur peut-on fabriquer l'alliage « Ardonite » ?", "200", 2, 25],
  ],
};
