// Fichier généré par tools/quetes_dofus.py : ne pas modifier à la main (relancer le script).
// Une question par quête des séries de quêtes des Dofus. Données : DofusDB.
export default {
  cat: "Quêtes",
  items: [
    ["À quel Dofus est reliée la quête « Retourner voir le Dark Vlad, toujours sans mourir » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Qui botte le cul des Culs Bottés ? » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Le voleur d'âmes » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « L'amour perdu de Nabur » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Naissance d'une vocation » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Les bandits de Cania » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Draconanthropie » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Ultime réminiscence » ?", "Dofus Émeraude", 2, 20],
    ["À quel Dofus est reliée la quête « Le livre des Taures » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Taures et détours » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Le trésor de Totankama » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Il faut battre le lait quand il est chaud » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Regrets d'éternailes » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « L'anneau de Tot » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Une âme en peine » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Le pouvoir derrière le trône » ?", "Dofus Pourpre", 2, 20],
    ["À quel Dofus est reliée la quête « Plongeon et dragon » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « Extinction des feux » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « On dirait le Sud » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « La méchante sorcière de l'Est » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « Autel du Nord » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « Il était une foi dans l'Ouest » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « La bénédiction de Viti » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « La bénédiction de Thomahon » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « La bénédiction de Foluk » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « Une âme en colère » ?", "Dofus Turquoise", 2, 20],
    ["À quel Dofus est reliée la quête « Le Dofus et l'alchimiste » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « La raison du plus fort » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Après lui, le déluge » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Comme un corbac sur sa branche » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Rester planté là » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Pas de fumée sans feu » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Quand les esprits s'échauffent » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Le serment de l'ambre » ?", "Dofus Ocre", 2, 20],
    ["À quel Dofus est reliée la quête « Le dragon blanc » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Examen de passage » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Le Pays Gris » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Casse en Enutrosor » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Nordalie » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Le bonheur est dans le spray » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Une voix de crystal » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Le mort dans l'âme » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Le guerrier noir » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « Il est temps de mourir » ?", "Dofus Ivoire", 2, 20],
    ["À quel Dofus est reliée la quête « L'épée du rocher » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Le forgeur de légende » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Jusqu'au bout du rêve » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « À la recherche de Crocoburio » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Le creuset de Mériana » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Une douloureuse séparation » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Le dragon noir » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « La vengeance du dernier empereur » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « L'œuf de Crocabulia » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Un nouvel héritier » ?", "Dofus Ébène", 2, 20],
    ["À quel Dofus est reliée la quête « Amaknanomalie » ?", "Dofus Vulbis", 2, 20],
    ["À quel Dofus est reliée la quête « La mère des Dragoeufs » ?", "Dofus Vulbis", 2, 20],
    ["À quel Dofus est reliée la quête « Cauchemar infini » ?", "Dofus Vulbis", 2, 20],
    ["À quel Dofus est reliée la quête « La Nuit-qui-rugit » ?", "Dofus Vulbis", 2, 20],
    ["À quel Dofus est reliée la quête « Les raisons de la colère » ?", "Dofus Vulbis", 2, 20],
    ["À quel Dofus est reliée la quête « Le temps des secrets » ?", "Dofus Vulbis", 2, 20],
    ["À quel Dofus est reliée la quête « La danse de la dissonance » ?", "Dofus du Cauchemar", 2, 20],
    ["À quel Dofus est reliée la quête « Descendre aux cendres » ?", "Dofus du Cauchemar", 2, 20],
    ["À quel Dofus est reliée la quête « Un héritage tourmenté » ?", "Dofus du Cauchemar", 2, 20],
    ["À quel Dofus est reliée la quête « Les totems de Maïmane » ?", "Dofus du Cauchemar", 2, 20],
    ["À quel Dofus est reliée la quête « Voyage, voyage » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « La porte d'Enutrosor » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Orichomania » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « La cité de l'indicible mal » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Messager clandestin » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « La voix de son maître » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Le maître des zaaps » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Énergie renouvelable » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Traitement de choc » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Le disparu de Sufokia » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Rendez-vous avec la mort » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Secret de fabrication » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « S'emparer des commandes » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « C'est dans la boîte » ?", "Dofus des Veilleurs", 2, 20],
    ["À quel Dofus est reliée la quête « Crise d'identité » ?", "Dofus des Veilleurs", 2, 20],
  ],
};
