// Une question par quête de chaque Dofus.
export default {
  cat: "Quêtes",
  items: [
    ["À quel Dofus est reliée la quête « Retourner voir le Dark Vlad, toujours sans mourir » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Qui botte le cul des Culs Bottés ? » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Le voleur d'âmes » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « L'amour perdu de Nabur » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Naissance d'une vocation » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Les bandits de Cania » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Draconanthropie » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Ultime réminiscence » ?", "Dofus Émeraude", 2, 20, "Dofus Émeraude"],
    ["À quel Dofus est reliée la quête « Le livre des Taures » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Taures et détours » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Le trésor de Totankama » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Il faut battre le lait quand il est chaud » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Regrets d'éternailes » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « L'anneau de Tot » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Une âme en peine » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Le pouvoir derrière le trône » ?", "Dofus Pourpre", 2, 20, "Dofus Pourpre"],
    ["À quel Dofus est reliée la quête « Plongeon et dragon » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « Extinction des feux » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « On dirait le Sud » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « La méchante sorcière de l'Est » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « Autel du Nord » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « Il était une foi dans l'Ouest » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « La bénédiction de Viti » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « La bénédiction de Thomahon » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « La bénédiction de Foluk » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « Une âme en colère » ?", "Dofus Turquoise", 2, 20, "Dofus Turquoise"],
    ["À quel Dofus est reliée la quête « Le Dofus et l'alchimiste » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « La raison du plus fort » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Après lui, le déluge » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Comme un corbac sur sa branche » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Rester planté là » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Pas de fumée sans feu » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Quand les esprits s'échauffent » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Le serment de l'ambre » ?", "Dofus Ocre", 2, 20, "Dofus Ocre"],
    ["À quel Dofus est reliée la quête « Le dragon blanc » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Examen de passage » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Le Pays Gris » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Casse en Enutrosor » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Nordalie » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Le bonheur est dans le spray » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Une voix de crystal » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Le mort dans l'âme » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Le guerrier noir » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « Il est temps de mourir » ?", "Dofus Ivoire", 2, 20, "Dofus Ivoire"],
    ["À quel Dofus est reliée la quête « L'épée du rocher » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Le forgeur de légende » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Jusqu'au bout du rêve » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « À la recherche de Crocoburio » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Le creuset de Mériana » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Une douloureuse séparation » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Le dragon noir » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « La vengeance du dernier empereur » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « L'œuf de Crocabulia » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Un nouvel héritier » ?", "Dofus Ébène", 2, 20, "Dofus Ébène"],
    ["À quel Dofus est reliée la quête « Amaknanomalie » ?", "Dofus Vulbis", 2, 20, "Dofus Vulbis"],
    ["À quel Dofus est reliée la quête « La mère des Dragoeufs » ?", "Dofus Vulbis", 2, 20, "Dofus Vulbis"],
    ["À quel Dofus est reliée la quête « Cauchemar infini » ?", "Dofus Vulbis", 2, 20, "Dofus Vulbis"],
    ["À quel Dofus est reliée la quête « La Nuit-qui-rugit » ?", "Dofus Vulbis", 2, 20, "Dofus Vulbis"],
    ["À quel Dofus est reliée la quête « Les raisons de la colère » ?", "Dofus Vulbis", 2, 20, "Dofus Vulbis"],
    ["À quel Dofus est reliée la quête « Le temps des secrets » ?", "Dofus Vulbis", 2, 20, "Dofus Vulbis"],
    ["À quel Dofus est reliée la quête « La danse de la dissonance » ?", "Dofus du Cauchemar", 2, 20, "Dofus du Cauchemar"],
    ["À quel Dofus est reliée la quête « Descendre aux cendres » ?", "Dofus du Cauchemar", 2, 20, "Dofus du Cauchemar"],
    ["À quel Dofus est reliée la quête « Un héritage tourmenté » ?", "Dofus du Cauchemar", 2, 20, "Dofus du Cauchemar"],
    ["À quel Dofus est reliée la quête « Les totems de Maïmane » ?", "Dofus du Cauchemar", 2, 20, "Dofus du Cauchemar"],
    ["À quel Dofus est reliée la quête « Voyage, voyage » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « La porte d'Enutrosor » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Orichomania » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « La cité de l'indicible mal » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Messager clandestin » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « La voix de son maître » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Le maître des zaaps » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Énergie renouvelable » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Traitement de choc » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Le disparu de Sufokia » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Rendez-vous avec la mort » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Secret de fabrication » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « S'emparer des commandes » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « C'est dans la boîte » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « Crise d'identité » ?", "Dofus des Veilleurs", 2, 20, "Dofus des Veilleurs"],
    ["À quel Dofus est reliée la quête « La quête de l'oiseau du temps » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Elle va finir par se faire coffrer » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Pompe à fric » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Koffrologie » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Trésorphelinat » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Malladie » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Crache Test » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La quatrième dimension » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Déphorrestation » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La meilleure défense, c'est l'attaque » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Phorreurs dans la brume » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Le phormidiable au corps » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La pelle de la Phorrée » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les grandes galeries » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Un cœur d'or » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Maudite générosité » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « On ne prête qu'à Richard » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Pour quelques kamas de plus » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Tout ce qui brille n'est pas or » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Un morceau de roi » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Prime de Lèche-Majesté » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Coiffeur de génie » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Touchez pas à Grisebigle » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Échantillonnage » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Le silence est d'or » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Espionnage industriel » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Prise d'otages » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La grève de la fin » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Malle des profondeurs » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Reconnaissance de dette » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Laissé en plan » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Ça katche ou ça casse » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Fanfouille » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La seinoise » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Ça se katche » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Un ring pour les gouverner tous » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Nécrotiques, tiques, tiques » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La pêche au poison » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les troupiers » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Épidémiologie » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Tique attaque » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Sa Majesté des Nécrotiques » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « L'art me ment » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Viande fraîche » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La morte Adèle » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Comme un poison dans l'eau » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les sentiers de la perdition » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Le Bazar du Bizarre » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Un Chafer dans le placard » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Bouchées à la reine » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La cour des miracles » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Os sitôt dit, aussitôt fait » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Faux-semblants » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Mémoires d'outre-tombe » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Balance la sauce » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La chapelle noire » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Présumé coupable » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Depuis l'enfer » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Courir après des ombres » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Sortir de l'ombre » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La grosse commission » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Anomalies temporelles » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « C'est ton destin » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Retour vers le présent » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Prisonniers du temps » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les voleurs de couleurs » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Terminutor : le jugement de la machine » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les démons de midi » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Aux origines du mal » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « De fil en aiguille » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La Vie, l'Hormonde et le Reste » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Failles spatio-temporelles » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « C'est quoi ton 06 ? » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Aujourd'hui à jamais » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Tout ce qu'il te faut, c'est tuer » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Juste une illusion » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Maboul de cristal » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « L'armée des 12 dingues » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « La vérité est au fond du puits » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les sables du temps » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Déchirures temporelles » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Futur antérieur » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Guerre temporelle » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « L'étendue Gödelique » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Les visiteurs du futur » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Demain ne meurt jamais » ?", "Dofus Nébuleux", 2, 20, "Dofus Nébuleux"],
    ["À quel Dofus est reliée la quête « Réponses à tout » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Le village dans les nuages » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Espoirs et tragédies » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Dans la gueule du Milimilou » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Destination Astrub » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Transport peu commun » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Des vestiges de légende » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Vu du ciel » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Mise à l'épreuve » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Champs de bataille » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Coups d'épée dans l'eau » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Décime-moi des bouftous » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Chasse aux chapardams » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Leçon d'humilité » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Des chafers qui marchent » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Produits naturels » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La hache et la pioche » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Boune un jour, boune toujours » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Le métier des aventuriers » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Préparation au combat » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La galette secrète » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Mort au rat ! » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Cryptologie » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Un peu de pigment » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Les principes d'Archie m'aident » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « On marche sur des œufs » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Conseil de classe » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Une vie de milichien » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Les paroles s'envolent, les aigris restent » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Un rayon de soleil » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « L'étrange créature de l'étang bleu » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Zobal Hibaba et les 40 Roublards » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Braquage à la Roublard » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Trempette dans un verre d'eau » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Souffre-douleur » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « C'est pourtant naturel » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « C'est pour ta pomme » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Iop et hop » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Piques de solution » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Au petit malheur la chance » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Tarot, t'es très fort » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Crime et châtiment » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La fête de la chocopépite » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Série animalière » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Tournée d'inspection » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La routine anodine du chevalier citadin » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Ça sent le gaz » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Balade en forêt » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Ça tombe à l'eau » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Six pieds sous terre » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Tel est pris qui croyait prendre » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « L'histoire en mouvement » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Restauration rapide » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « De vrais rats de bibliothèque » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Légende d'automne » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Bière qui roule n'amasse pas mousse » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Combat de rue » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Comme un pichon hors de l'eau » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Déjeuner à la fourchette » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La coupe des vices » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Les as de la cambriole » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Crise sanitaire » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Livraison par intérim » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Golémancien » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Le rebelle de la forêt » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Chacha Blues » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Les deux font l'impair » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Attention à la Bête ! » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La petite mission dans la prairie » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Qui sème le vent récolte l'Artempeth » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Bûcherons en détresse » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Le génie se meut » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « L'invasion des profanateurs de sépultures » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « Le repos est dans le champ » ?", "Dofus Argenté", 2, 20, "Dofus Argenté"],
    ["À quel Dofus est reliée la quête « La pêche aux infos » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Le héros de Sufokia » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Il y a de l'électricité dans l'eau » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Topo le petit robot » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Piège de crystal » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Son nom est Personne » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « La clef de l'énigme » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Une porte vers le passé » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Reine de beauté » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Rançon nage » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Stratégie en Trithon Réel » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Sur fond de crise » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Risquer un œil » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « La gueule de l'enfer » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Celle qui glougloutait dans les ténèbres » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « L'affaire Pollie Perkine » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Trop Pollie pour être honnête » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Quand les astres seront propices » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Il suffira d'un signe » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « De mal en impie » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Le vieux gob et la mer » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Demain, j'arête » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « L'effet Paula Rice » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Fhtagn ! » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Les sept Mercemers » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Nos chairs voisines » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Concurrence déloyale » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Qui a la plus grosse ? » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Droit de cuissage » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « La musique de Rykke Zane » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Mémoires d'un amnésique » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « L'odeur devant le seuil » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Aux grands mots les grands remèdes » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « L'ivresse des profondeurs » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Les Mercemers sont bien outillés » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Pêche aux krabouilleurs » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « À bas Kralab Rah » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « KO pour Bosko Tho » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Relevez les niveaux » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « Prise de notes » ?", "Dofus Abyssal", 2, 20, "Dofus Abyssal"],
    ["À quel Dofus est reliée la quête « La terre banquise » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La maire de glace » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Full contact » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Antiroyaliste » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Les joyeux de la couronne » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Fais dodo, t'auras du gâteau » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Lavomatique » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « C'est frais, mais c'est pas grave » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Sans ma barbe, quelle barbe » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Là-haut sur la montagne » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Le pic qui glace » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Bienvenue à Frigost » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « L'essentiel est dans Lac Gelé » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Les rescapés de Frigost » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Frigost, une île pas comme les autres » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Développement durable » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Donjons et trouffions » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Au fion du trou » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Les rescapés du Village Enseveli » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Les derniers rescapés » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La vie de château » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La machine à démonter le temps » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Il faut mettre un terme aux maîtres » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Un comte de faits divers » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La destinée » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La fatalité » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La rivalité » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Malédiction ! » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Mission Solution » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Chaud et froid » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Le givre des révélations » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « Le Dofus des Glaces » ?", "Dofus des Glaces", 2, 20, "Dofus des Glaces"],
    ["À quel Dofus est reliée la quête « La colère des dieux » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « L'arme fatale » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Les cœurs livides » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « La guerre des Marches » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « La quête sous l'eau » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Craquements de cœur » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Cœur de pierre » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Les pierres à feu » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Du feu de dieu » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Plantes contre Trépamorts » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Le héros de Plantes contre Trépamorts » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Battre le fer tant qu'il est chaud » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Algue au rythme » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Au-delà de la Côte » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « La croisière, ça m'use » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Toucher le fond » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « La mort de ma vie » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Krobe en bourg » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Aventure miniature » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Ne tirez pas sur le messager » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « À la rescousse des magypus » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Dernier contact » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « La voix des morts » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Le fléau de Burin » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Le gang des Toxines » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Sombres desseins » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Le jour des assassins » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Le piège se referme » ?", "Dofus Forgelave", 2, 20, "Dofus Forgelave"],
    ["À quel Dofus est reliée la quête « Main dans la main » ?", "Dofus Tacheté", 2, 20, "Dofus Tacheté"],
    ["À quel Dofus est reliée la quête « Deux souffles, une inspiration » ?", "Dofus Tacheté", 2, 20, "Dofus Tacheté"],
    ["À quel Dofus est reliée la quête « En ce jardin qui nous unit » ?", "Dofus Tacheté", 2, 20, "Dofus Tacheté"],
  ],
};
