// Fichier généré par tools/succes_donjons_dofus.py : ne pas modifier à la main (relancer le script).
// Pour chaque donjon : ses 2 succès de challenge (hors Duo) et son succès spécial.
export default {
  cat: "Succès",
  items: [
    {"q": "Quels sont les 2 succès du donjon « Crypte de Kardorim », ainsi que son succès spécial ?", "champs": [["Succès 1", "Zombie"], ["Succès 2", "Premier"], ["Succès spécial", "Lâche mes côtes : Kardorim ne doit jamais terminer son tour au contact d'un combattant. Les Kardoribs ne doivent pas subir de dommages, ni être poussés."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Grange du Tournesol Affamé », ainsi que son succès spécial ?", "champs": [["Succès 1", "Collant"], ["Succès 2", "Premier"], ["Succès spécial", "Mauvaise graine : Les invocations du Tournesol Affamé doivent systématiquement être achevées avant le début de leur deuxième tour de jeu."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Château Ensablé », ainsi que son succès spécial ?", "champs": [["Succès 1", "Misanthrope"], ["Succès 2", "Versatile"], ["Succès spécial", "Passer l'éponge : À partir du tour 2, Mob l'éponge doit être poussé ou attiré au moins une fois à chaque tour global."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Cour du Bouftou Royal », ainsi que son succès spécial ?", "champs": [["Succès 1", "Prudent"], ["Succès 2", "Blitzkrieg"], ["Succès spécial", "Un Mulou dans la Bergerie : Les ennemis ne doivent pas recevoir de soin."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Donjon des Scarafeuilles », ainsi que son succès spécial ?", "champs": [["Succès 1", "Zombie"], ["Succès 2", "Mains propres"], ["Succès spécial", "Dorée, mi fa sol : Les invocations ennemies ne doivent subir aucun dommage."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Donjon des Tofus », ainsi que son succès spécial ?", "champs": [["Succès 1", "Statue"], ["Succès 2", "Versatile"], ["Succès spécial", "Bécotam : Lorsque les combattants alliés infligent des dommages aux ennemis, ils doivent être en ligne de ces derniers."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Maison Fantôme », ainsi que son succès spécial ?", "champs": [["Succès 1", "Misanthrope"], ["Succès 2", "Dernier"], ["Succès spécial", "Empêtrement d'esprit entêtant : Aucun Ashi-magari ne doit être achevé pendant toute la durée du combat."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Donjon des Squelettes », ainsi que son succès spécial ?", "champs": [["Succès 1", "Nomade"], ["Succès 2", "Premier"], ["Succès spécial", "Désillusion : Aucune illusion du Chafer Rōnin ne doit être présente au début de son tour."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Donjon des Bworks », ainsi que son succès spécial ?", "champs": [["Succès 1", "Misanthrope"], ["Succès 2", "Premier"], ["Succès spécial", "Tombés sous le charme : Les ennemis ne doivent être achevés que par des combattants dans l'état insoignable."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Donjon des Forgerons », ainsi que son succès spécial ?", "champs": [["Succès 1", "Nomade"], ["Succès 2", "Premier"], ["Succès spécial", "Ouverture facile : Les ennemis doivent être achevés uniquement lorsque le Coffre des Forgerons possède moins de 50 % de sa vie. Le challenge échoue si le Coffre des Forgerons n'est pas achevé en dernier."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Donjon des Larves », ainsi que son succès spécial ?", "champs": [["Succès 1", "Prudent"], ["Succès 2", "Versatile"], ["Succès spécial", "Enlisement larvaire : Les alliés ne doivent infliger des dégats qu'au Shin Larve lorsqu'ils sont sous l'effet du sort Enlisement."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Grotte Hesque », ainsi que son succès spécial ?", "champs": [["Succès 1", "Hardi"], ["Succès 2", "Blitzkrieg"], ["Succès spécial", "Collé-serré : À partir du tour global 2, les combattants alliés doivent commencer leur tour au contact du Corailleur Magistral. Le challenge échoue si le Corailleur Magistral n'est pas achevé en dernier."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Nid du Kwakwa », ainsi que son succès spécial ?", "champs": [["Succès 1", "Zombie"], ["Succès 2", "Mains propres"], ["Succès spécial", "Kwakwa ? Kwapoussée ! : Les ennemis ne doivent pas subir de dommages de poussée."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Cache de Kankreblath », ainsi que son succès spécial ?", "champs": [["Succès 1", "Collant"], ["Succès 2", "Dernier"], ["Succès spécial", "La ligne interdite : Les alliés (hors invocations statiques) ne doivent terminer leur tour ni en ligne d'un ennemi, ni en ligne d'un autre allié."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Akadémie des Gobs », ainsi que son succès spécial ?", "champs": [["Succès 1", "Nomade"], ["Succès 2", "Premier"], ["Succès spécial", "Dirige mais mal rédige : À partir du tour 2, les combattants ennemis doivent commencer leur tour sur une cellule adjacente à celle d'un allié ou d'un ennemi."]], "pts": 3, "temps": 45},
    {"q": "Quels sont les 2 succès du donjon « Refuge Sylvestre », ainsi que son succès spécial ?", "champs": [["Succès 1", "Dernier"], ["Succès 2", "Prudent"], ["Succès spécial", "Vigilance forestière : Les alliés ne doivent pas cumuler plus de deux faiblesses élémentaires différentes au début de leur tour."]], "pts": 3, "temps": 45},
  ],
};
